export interface Product {
  id: number
  name: string
  category: string
  subcategory: string
  description: string
  fullDescription: string
  image: string
  gallery: string[]
  price: number
  originalPrice?: number
  rating: number
  reviews: number
  inStock: boolean
  stockCount: number
  badge?: string
  badgeColor?: 'emerald' | 'amber' | 'red' | 'blue'
  specifications: Record<string, string>
  features: string[]
  certifications: string[]
  warranty: string
  shipping: {
    free: boolean
    estimatedDays: string
  }
  seller: {
    name: string
    rating: number
    reviews: number
    responseTime: string
  }
  returns: string
}

export const productsData: Product[] = [
  {
    id: 1,
    name: 'Professional Digital Stethoscope with AI-Enabled Diagnosis',
    category: 'Diagnostic Equipment',
    subcategory: 'Stethoscopes',
    description: 'Advanced digital stethoscope with AI noise cancellation, cloud recording, and heart sound analysis',
    fullDescription:
      'The Satyavij Professional Digital Stethoscope is engineered for modern healthcare professionals who demand precision and reliability. Featuring cutting-edge AI technology, this device automatically cancels ambient noise while recording and analyzing heart and lung sounds with 95% accuracy. Perfect for cardiology, pulmonology, and primary care clinics.',
    image: '/images/product-stethoscope.jpg',
    gallery: ['/images/product-stethoscope.jpg', '/images/product-stethoscope.jpg'],
    price: 299,
    originalPrice: 449,
    rating: 4.8,
    reviews: 1247,
    inStock: true,
    stockCount: 45,
    badge: 'Best Seller',
    badgeColor: 'emerald',
    specifications: {
      'Frequency Range': '20 Hz - 20 kHz',
      'Noise Reduction': 'AI-Powered (95% effective)',
      'Recording Capacity': '500+ hours',
      'Battery Life': '12 hours',
      'Weight': '120g',
      'Material': 'Medical-grade aluminum & stainless steel',
    },
    features: [
      'AI-powered noise cancellation technology',
      'Cloud-based sound recording and analysis',
      'Real-time heart rate detection',
      'Mobile app integration',
      'Compatible with Electronic Health Records (EHR)',
      'Wireless Bluetooth connectivity',
      'Durable medical-grade construction',
      'Multiple earpiece sizes included',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'ISO 13485 Medical Device Standard'],
    warranty: '5-Year Manufacturer Warranty',
    shipping: {
      free: true,
      estimatedDays: '2-3 business days',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: '30-day money-back guarantee | Free returns within 30 days',
  },
  {
    id: 2,
    name: 'Portable Pulse Oximeter with OLED Display',
    category: 'Monitoring Equipment',
    subcategory: 'Pulse Oximeters',
    description: 'Compact and accurate pulse oximeter for continuous SpO2 and heart rate monitoring',
    fullDescription:
      'The Satyavij Pulse Oximeter combines portability with medical-grade accuracy. With its OLED display and advanced photodiode technology, it provides real-time SpO2 and heart rate readings in under 5 seconds. Ideal for home monitoring, sports medicine, and clinical use.',
    image: '/images/product-pulse-oximeter.jpg',
    gallery: ['/images/product-pulse-oximeter.jpg'],
    price: 49,
    originalPrice: 79,
    rating: 4.7,
    reviews: 3456,
    inStock: true,
    stockCount: 128,
    badge: 'Budget-Friendly',
    badgeColor: 'blue',
    specifications: {
      'Measurement Range': 'SpO2: 70-100%, PR: 30-250 bpm',
      'Accuracy': '±2% SpO2, ±2 bpm Heart Rate',
      'Display': 'OLED, 0.96" diagonal',
      'Battery': 'AAA (2 required), 16-30 hours',
      'Weight': '45g (without batteries)',
      'Operating Temp': '5-40°C',
    },
    features: [
      'Fast 5-second measurement time',
      'Large OLED display with 8 color options',
      'Low battery indicator',
      'Data storage for 24 measurements',
      'Automatic shutoff after 8 seconds',
      'Lightweight and portable design',
      'Non-invasive measurement',
    ],
    certifications: ['FDA Approved', 'CE Marked', 'RoHS Compliant'],
    warranty: '1-Year Warranty',
    shipping: {
      free: true,
      estimatedDays: '1-2 business days',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: '30-day easy returns | 60-day return window for medical products',
  },
  {
    id: 3,
    name: 'Automatic Digital Blood Pressure Monitor with Irregular Heartbeat Detection',
    category: 'Monitoring Equipment',
    subcategory: 'BP Monitors',
    description: 'Advanced BP monitor with WHO classification and intelligent heartbeat analysis',
    fullDescription:
      'Professional-grade blood pressure monitor designed for accurate home and clinical monitoring. Features intelligent irregular heartbeat detection, large backlit display, and WHO classification system. Perfect for hypertension management and preventive care.',
    image: '/images/product-bp-monitor.jpg',
    gallery: ['/images/product-bp-monitor.jpg'],
    price: 89,
    originalPrice: 149,
    rating: 4.9,
    reviews: 2834,
    inStock: true,
    stockCount: 67,
    badge: 'Top Rated',
    badgeColor: 'emerald',
    specifications: {
      'Measurement Range': 'SYS: 90-260 mmHg, DIA: 60-180 mmHg',
      'Accuracy': '±3 mmHg standard deviation',
      'Memory': '120 readings with date/time',
      'Cuff Size': '22-32 cm (adjustable)',
      'Power': '4 AA batteries',
      'Display': '1.3" LCD with backlight',
    },
    features: [
      'Irregular heartbeat detection (IHD)',
      'WHO classification (Normal, Elevated, Stage 1, Stage 2)',
      'Dual user profiles with 120 memory slots each',
      'Large easy-to-read LCD display',
      'Quick measurement in 30-40 seconds',
      'Comfortable arm cuff design',
      'Portable and travel-friendly',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'Clinically Validated'],
    warranty: '3-Year Warranty',
    shipping: {
      free: true,
      estimatedDays: '2-3 business days',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: '30-day money-back guarantee',
  },
  {
    id: 4,
    name: 'Multi-Parameter Patient Monitor with Wi-Fi Connectivity',
    category: 'Patient Monitoring',
    subcategory: 'Vital Sign Monitors',
    description: 'Comprehensive vital signs monitor for hospitals and clinics with cloud integration',
    fullDescription:
      'Enterprise-grade patient monitor that simultaneously tracks ECG, SpO2, heart rate, blood pressure, temperature, and respiration. Features real-time alerts, cloud connectivity for remote monitoring, and intuitive touchscreen interface.',
    image: '/images/product-monitor.jpg',
    gallery: ['/images/product-monitor.jpg'],
    price: 2499,
    originalPrice: 3999,
    rating: 4.8,
    reviews: 456,
    inStock: true,
    stockCount: 12,
    badge: 'Hospital Grade',
    badgeColor: 'amber',
    specifications: {
      'Display': '12.1" high-resolution LCD touchscreen',
      'Parameters': '6 simultaneous measurements',
      'Storage': '72 hours of continuous data',
      'Connectivity': 'Wi-Fi, Ethernet, USB',
      'Power': '24V DC with battery backup (8 hours)',
      'Alarm Capability': '60+ configurable alarms',
    },
    features: [
      'Real-time patient data monitoring',
      'Cloud-based remote monitoring capability',
      'Automatic alarm escalation',
      'Trend analysis and reporting',
      'Compatible with major hospital systems',
      'HIPAA-compliant data encryption',
      'Mobile app for doctors and nurses',
      'Continuous 72-hour data recording',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'HIPAA Compliant'],
    warranty: '5-Year Full Service Warranty',
    shipping: {
      free: true,
      estimatedDays: '5-7 business days (Installation included)',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: '90-day satisfaction guarantee | Free installation support',
  },
  {
    id: 5,
    name: 'Portable 12-Lead ECG Machine with Automatic Interpretation',
    category: 'Diagnostic Equipment',
    subcategory: 'ECG Machines',
    description: 'Lightweight portable ECG device with AI-powered automatic interpretation and reporting',
    fullDescription:
      'Revolutionary portable ECG machine that weighs just 1.2 kg yet provides hospital-quality 12-lead recordings. Advanced AI engine automatically analyzes and interprets ECG patterns, detecting arrhythmias and abnormalities with 96% accuracy.',
    image: '/images/product-ecg.jpg',
    gallery: ['/images/product-ecg.jpg'],
    price: 1999,
    originalPrice: 2999,
    rating: 4.7,
    reviews: 678,
    inStock: true,
    stockCount: 24,
    badge: 'Innovation',
    badgeColor: 'blue',
    specifications: {
      'Channels': '12-lead simultaneous recording',
      'Paper Speed': '25 mm/s',
      'Recording Speed': '10 seconds for complete ECG',
      'Storage': '1000+ ECG records',
      'Weight': '1.2 kg',
      'Battery': '4 hours continuous use',
    },
    features: [
      'AI-powered automatic interpretation',
      'High-resolution thermal printer included',
      'USB and SD card data export',
      'Portable carrying case',
      'Multi-language support',
      'Telemedicine integration',
      'Instant PDF report generation',
      'Compatible with EMR systems',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'IEC 60601-2-25'],
    warranty: '4-Year Warranty',
    shipping: {
      free: true,
      estimatedDays: '3-4 business days',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: '45-day satisfaction guarantee',
  },
  {
    id: 6,
    name: 'Smart Thermometer with Temperature Trend Analysis',
    category: 'Diagnostic Equipment',
    subcategory: 'Thermometers',
    description: 'Infrared thermometer with app integration and historical temperature tracking',
    fullDescription:
      'Non-contact infrared thermometer providing accurate readings in 1 second. Smart app tracks temperature trends, sends alerts for fever, and maintains medical records. Perfect for clinics, pharmacies, and home use.',
    image: '/images/product-pulse-oximeter.jpg',
    gallery: ['/images/product-pulse-oximeter.jpg'],
    price: 35,
    originalPrice: 65,
    rating: 4.6,
    reviews: 2145,
    inStock: true,
    stockCount: 200,
    badge: 'New',
    badgeColor: 'emerald',
    specifications: {
      'Temperature Range': '34-42.5°C',
      'Accuracy': '±0.2°C',
      'Reading Time': '1 second',
      'Distance': '5-15 cm for accurate reading',
      'Power': '2 AAA batteries',
      'Display': 'LED digital display',
    },
    features: [
      'Non-contact measurement (safer)',
      'Smart app with Bluetooth connectivity',
      'Fever alert notifications',
      'Temperature history tracking',
      '100-record memory',
      'Backlit display for night use',
      'Waterproof and durable',
      'WHO fever guidelines built-in',
    ],
    certifications: ['FDA Approved', 'CE Certified'],
    warranty: '2-Year Warranty',
    shipping: {
      free: true,
      estimatedDays: '1-2 business days',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: '30-day returns | 60-day extended return for medical use',
  },
  {
    id: 7,
    name: 'Surgical LED Operating Light with Camera Integration',
    category: 'Operating Room',
    subcategory: 'Surgical Lights',
    description: 'Professional surgical light with integrated HD camera and recording capabilities',
    fullDescription:
      'Premium operating light designed for surgical suites and procedure rooms. Features ultra-bright LED technology, automatic color temperature control, and integrated HD camera for surgical documentation and training.',
    image: '/images/product-monitor.jpg',
    gallery: ['/images/product-monitor.jpg'],
    price: 5999,
    originalPrice: 8499,
    rating: 4.9,
    reviews: 234,
    inStock: false,
    stockCount: 0,
    badge: 'Premium',
    badgeColor: 'amber',
    specifications: {
      'Illumination': '80,000 - 160,000 lux',
      'Color Temperature': '3000-6500K adjustable',
      'Camera Resolution': '4K (3840x2160)',
      'Operating Distance': '1-2 meters',
      'Power': '220V AC',
      'Warranty': 'Lifetime LED',
    },
    features: [
      'Ultra-bright LED technology',
      'Integrated 4K HD camera',
      'Live streaming capability',
      'Automatic color temperature adjustment',
      'Zero shadow surgical field',
      'Easy arm positioning',
      'Touchless controls available',
      'DICOM compatible recording',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'IEC 60601-1'],
    warranty: 'Lifetime LED + 5-Year Full Warranty',
    shipping: {
      free: true,
      estimatedDays: '10-14 business days (Professional installation)',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: 'Pre-order available | Installation support included',
  },
  {
    id: 8,
    name: 'Ultrasound Machine - Portable B-Mode Ultrasound',
    category: 'Diagnostic Equipment',
    subcategory: 'Ultrasound Systems',
    description: 'Portable B-mode ultrasound with 4 interchangeable probes for versatile imaging',
    fullDescription:
      'Compact yet powerful portable ultrasound system with multiple probe options for abdominal, cardiac, and soft tissue imaging. Features real-time imaging, DICOM compliance, and battery backup for field use.',
    image: '/images/product-stethoscope.jpg',
    gallery: ['/images/product-stethoscope.jpg'],
    price: 12999,
    originalPrice: 17999,
    rating: 4.8,
    reviews: 167,
    inStock: true,
    stockCount: 5,
    badge: 'Enterprise',
    badgeColor: 'blue',
    specifications: {
      'Display': '10" color LCD touchscreen',
      'Imaging Modes': 'B-Mode, M-Mode, Doppler',
      'Probes Included': '4 (Convex, Linear, Phased, Sector)',
      'Image Storage': '50,000+ images',
      'Video Storage': '500 hours',
      'Power': '24V DC with 8-hour battery',
    },
    features: [
      'Real-time B-mode imaging',
      'Advanced Doppler capabilities',
      'DICOM network integration',
      'USB and SD card export',
      'Telemedicine connectivity',
      'Multiple measurement tools',
      'Clinical protocol library',
      'Teaching mode for training',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'DICOM 3.0'],
    warranty: '3-Year Warranty + Free Probe Replacement',
    shipping: {
      free: true,
      estimatedDays: '7-10 business days',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: '90-day trial period available',
  },
  {
    id: 9,
    name: 'Automated Drug Dispensing System',
    category: 'Pharmacy Equipment',
    subcategory: 'Dispensing Systems',
    description: 'Intelligent medication dispensing system with inventory management and barcode verification',
    fullDescription:
      'Advanced robotic medication dispensing system that reduces medication errors by 99%. Features barcode verification, real-time inventory tracking, and integration with pharmacy management systems.',
    image: '/images/product-bp-monitor.jpg',
    gallery: ['/images/product-bp-monitor.jpg'],
    price: 24999,
    originalPrice: 34999,
    rating: 4.9,
    reviews: 89,
    inStock: false,
    stockCount: 0,
    badge: 'Custom',
    badgeColor: 'amber',
    specifications: {
      'Medication Capacity': '2000+ medications',
      'Accuracy': '99.9% error detection',
      'Throughput': '600+ dispensing cycles/hour',
      'Power': '3-phase 380V AC',
      'Interface': 'Touchscreen + POS integration',
      'System Integration': 'Hospital + Pharmacy ERP',
    },
    features: [
      'Real-time barcode verification',
      'Automated inventory management',
      'Medication interaction checking',
      'Integration with EHR systems',
      'Staff role-based access control',
      'Comprehensive audit trail',
      'Remote diagnostics capability',
      'Multi-language support',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'GxP Compliant'],
    warranty: '5-Year Comprehensive Warranty',
    shipping: {
      free: true,
      estimatedDays: '30-45 days (Custom setup + training)',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: 'Lease options available | Free training included',
  },
  {
    id: 10,
    name: 'Hospital Grade Bed with Integrated Vital Sign Monitor',
    category: 'Patient Care',
    subcategory: 'Hospital Beds',
    description: 'Smart hospital bed with pressure relief, patient movement tracking, and vital sign monitoring',
    fullDescription:
      'Advanced hospital bed featuring pressure relief technology to prevent bedsores, integrated vital sign monitoring system, and smart movement tracking for fall prevention and patient care optimization.',
    image: '/images/product-pulse-oximeter.jpg',
    gallery: ['/images/product-pulse-oximeter.jpg'],
    price: 8999,
    originalPrice: 12999,
    rating: 4.7,
    reviews: 145,
    inStock: true,
    stockCount: 8,
    badge: 'Premium Care',
    badgeColor: 'emerald',
    specifications: {
      'Bed Length': '190-210 cm (adjustable)',
      'Weight Capacity': '300 kg',
      'Adjustment Positions': '5 electric motors',
      'Pressure Relief': 'Dynamic air mattress',
      'Power': '220V AC with battery backup',
      'Dimensions': '210 x 105 x 65-85 cm',
    },
    features: [
      'Electric height adjustment',
      'Patient fall detection sensor',
      'Integrated vital sign monitoring',
      'Automatic pressure relief system',
      'Remote control included',
      'Easy manual control option',
      'Washable mattress covers',
      'Fire-retardant materials',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'ISO 9001'],
    warranty: '5-Year Warranty on Frame + 3-Year on Electronics',
    shipping: {
      free: true,
      estimatedDays: '14-21 days (Installation included)',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: '60-day trial period available for bulk orders',
  },
  {
    id: 11,
    name: 'Automatic Defibrillator (AED) with GPS Integration',
    category: 'Emergency Equipment',
    subcategory: 'Defibrillators',
    description: 'Portable AED with real-time CPR guidance and emergency responder tracking',
    fullDescription:
      'Professional automated external defibrillator featuring voice-guided CPR instructions, real-time responder dispatch integration, and telemetry data logging for post-incident analysis.',
    image: '/images/product-monitor.jpg',
    gallery: ['/images/product-monitor.jpg'],
    price: 2199,
    originalPrice: 3499,
    rating: 4.8,
    reviews: 312,
    inStock: true,
    stockCount: 19,
    badge: 'Lifesaver',
    badgeColor: 'red',
    specifications: {
      'Shock Energy': '150-360J adjustable',
      'Response Time': '< 10 seconds',
      'CPR Guidance': 'Real-time voice prompts',
      'Battery Life': '4 years',
      'Data Logging': 'Full incident recording',
      'Weight': '2.6 kg',
    },
    features: [
      'Voice-guided CPR instructions',
      'Automatic defibrillation protocol',
      'GPS emergency dispatch integration',
      'Telemetry data transmission',
      'Low maintenance design',
      'Portable carry case included',
      'Pediatric pads available',
      'Universal electrode compatibility',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'IEC 60601-2-4'],
    warranty: 'Lifetime Device + 4-Year Battery',
    shipping: {
      free: true,
      estimatedDays: '2-3 business days',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: 'Emergency replacement guarantee',
  },
  {
    id: 12,
    name: 'Medical Oxygen Concentrator - 10L/min Capacity',
    category: 'Respiratory Equipment',
    subcategory: 'Oxygen Systems',
    description: 'High-capacity oxygen concentrator for continuous home and clinical oxygen therapy',
    fullDescription:
      'Clinical-grade oxygen concentrator producing up to 10 liters of oxygen per minute at 93% concentration. Designed for 24/7 operation with multiple outlet ports, humidifier, and backup battery system.',
    image: '/images/product-stethoscope.jpg',
    gallery: ['/images/product-stethoscope.jpg'],
    price: 3999,
    originalPrice: 5999,
    rating: 4.7,
    reviews: 456,
    inStock: true,
    stockCount: 15,
    badge: 'Essential',
    badgeColor: 'emerald',
    specifications: {
      'Oxygen Output': '10 L/min',
      'Oxygen Concentration': '93% ± 3%',
      'Operating Hours': '24/7 continuous',
      'Power': '220V AC (dual motors)',
      'Weight': '34 kg',
      'Noise Level': '< 50 dB',
    },
    features: [
      'Dual oxygen outlet ports',
      'Integrated humidifier',
      'Adjustable flow rate (1-10 L/min)',
      'Low oxygen concentration alarm',
      'Hour meter for maintenance tracking',
      'Portable cart included',
      'Filter change indicator',
      '5-liter oxygen tank backup included',
    ],
    certifications: ['FDA Approved', 'CE Certified', 'ISO 8359'],
    warranty: '3-Year Warranty + Free Maintenance Service',
    shipping: {
      free: true,
      estimatedDays: '5-7 business days',
    },
    seller: {
      name: 'Satyavij Official Store',
      rating: 4.9,
      reviews: 5432,
      responseTime: '< 1 hour',
    },
    returns: '30-day satisfaction guarantee',
  },
]
